export { useAuditLog } from './useAuditLog';
export { useAuditFilter, type AuditFilterOptions } from './useAuditFilter';
export { useGeneratePassword } from './useGeneratePassword';
export { useRolePermissions, ROLE_PERMISSIONS_MAP, ALL_PERMISSIONS } from './useRolePermissions';
export type { UserRole, UserPermission } from './useRolePermissions';
export { useSimilarReports } from './useSimilarReports';
export type { SimilarReport, UseSimilarReportsOptions, UseSimilarReportsResult } from './useSimilarReports';
export { useLoginAttempts } from './useLoginAttempts';
export { useMenuVisibility, type MenuItem } from './useMenuVisibility';
export { useEntityPermissions, entityPermissionMap } from './useEntityPermissions';
export { useRegisterForm } from './useRegisterForm';
export { useSessionPersistence } from './useSessionPersistence';
export { useSignIn } from './useSignIn';
export { useSignOut } from './useSignOut';
export { useValidateEmail } from './useValidateEmail';
export { useFirstUserRegistration } from './useFirstUserRegistration';
export { usePublicRegistration } from './usePublicRegistration';
export { useResetPassword } from './useResetPassword';
export { useChangePassword } from './useChangePassword';
export { useChangeUserEmail } from './useChangeUserEmail';
export { useChangeUserPassword } from './useChangeUserPassword';
export { useUserLocation, type UserLocation, type UseUserLocationReturn } from './useUserLocation';
export { useLocationSync, type UseLocationSyncOptions, type UseLocationSyncReturn } from './useLocationSync';
export { useFormNavigation, type FormNavigationOptions, type FormNavigationResult } from './useFormNavigation';
export { useCategoryCheck } from './useCategoryCheck';
export { useCategoryCreatedDialog } from './useCategoryCreatedDialog';
export { useCloudinaryUpload, type CloudinaryUploadResult, type UploadProgress, type UseCloudinaryUploadOptions, type UseCloudinaryUploadReturn } from './useCloudinaryUpload';
export { useBulkResendConfirmation } from './useBulkResendConfirmation';
export { useNotifications, type NotificationFilter, type NotificationStats, type UseNotificationsOptions, type UseNotificationsReturn } from './useNotifications';
export { useNotificationCount } from './useNotificationCount';
export { useNotificationSync, emitNotificationEvent } from './useNotificationSync';
export { useBulkActions, type BulkActionConfig, type BulkActionsResult, type BulkActionType } from './useBulkActions';
export { useScalableBulkActions, type ScalableBulkActionConfig, type ScalableBulkActionsResult, type BulkDeleteResult } from './useScalableBulkActions';
export { useBulkUpload, type BulkUploadConfig, type BulkUploadRow, type BulkUploadStats, type FieldConfig, type RowStatus, type EntityType, type UseBulkUploadReturn } from './useBulkUpload';
export { useDashboardStats, type DashboardStats, type ChartDataPoint, type StatusDistribution, type PriorityDistribution, type RoleDistribution, type UseDashboardStatsReturn } from './useDashboardStats';
export { useDashboardRefresh } from './useDashboardRefresh';
export { useReportesAnalysis, type ReportesAnalysisStats, type ReportesStatusData, type ReportesPriorityData, type ReportesTrendData, type ReportesVisibilityData } from './useReportesAnalysis';
export { useUsuariosAnalysis, type UsuariosAnalysisStats, type UsuariosEstadoData, type UsuariosActividadData, type UsuariosCrecimientoData } from './useUsuariosAnalysis';
export { useTiposAnalysis, type TiposAnalysisStats, type TipoDistribution, type TiposPorCategoriaData } from './useTiposAnalysis';
export { useComparisonFilters, type FilterTab, type DateRange, type ComparisonFiltersState, type FilterOption, type ComparisonFiltersConfig, type UseComparisonFiltersReturn } from './useComparisonFilters';
export { useActivityPeak, type DrillLevel, type DrillState, type ActivityPeakStats, type YearlyTrendData, type MonthlyDistributionData, type DailyDistributionData, type HeatmapCell, type UseActivityPeakConfig, type UseActivityPeakReturn } from './useActivityPeak';
export { useOverpassAreas, AREA_TYPE_COLORS, AREA_TYPE_ICONS } from './useOverpassAreas';
export type { OSMNode, OSMArea, OSMAreaType } from './useOverpassAreas';
export { useOSMLocationData, type OSMLocationData } from './useOSMLocationData';
export { useChartToggle, type ChartType, type ChartDataItem, type UseChartToggleConfig, type UseChartToggleReturn } from './useChartToggle';
export { useEntityAnalysis, type UseEntityAnalysisReturn, type EntityAnalysisConfig, type EntityStats } from './useEntityAnalysis';
export { useUsuariosEntityAnalysis, type UseUsuariosEntityAnalysisReturn } from './useUsuariosEntityAnalysis';
export { useNearbyReportNotifications, type NearbyReportPayload } from './useNearbyReportNotifications';
export { useCreatePublicacion, usePublicacionInteractions as usePublicacionInteractionsLegacy, type CreatePublicacionInput, type UseCreatePublicacionOptions } from './useCreatePublicacion';
export { useAutoShareReport } from './useAutoShareReport';
export { usePostViews, useRegisterPostView, clearPostViewsCache, prefetchPostViews } from './usePostViews';
export { usePublicacionInteractions, prefetchPublicacionInteractions, clearInteractionsCache } from './usePublicacionInteractions';
export { usePushNotifications, type NotificationPermissionState } from './usePushNotifications';
export { useFriendRequestNotifications } from './useFriendRequestNotifications';
export { useRouteProtection, useCanAccessRoute, routeConfigurations, findRouteConfig, type RouteConfig, type UseRouteProtectionResult } from './useRouteProtection';
export { useSmartReportAnalysis, findBestCategoryMatch, findBestTipoMatch, type AnalysisResult, type UseSmartReportAnalysisReturn } from './useSmartReportAnalysis';
export { useNearbyAssignableUsers, type NearbyUser, type UseNearbyAssignableUsersOptions, type UseNearbyAssignableUsersReturn } from './useNearbyAssignableUsers';
export { useReportAssignmentNotification } from './useReportAssignmentNotification';
export { useReportAssignmentMessage, extractReportDetails } from './useReportAssignmentMessage';
export { useActiveTracking, type TrackingWithDetails, type UserLocationRealtime, type UseActiveTrackingReturn } from './useActiveTracking';
export { useRealtimeNavigation, type NavigationDestination, type NavigationStats, type ReportForNavigation, type UseRealtimeNavigationReturn } from './useRealtimeNavigation';
export { useReporteHistorialActions, type ReporteHistorialTipo, type CreateHistorialParams, type CreateBulkHistorialParams } from './useReporteHistorialActions';
